import React from 'react'
import "./App.scss"
import Container from "react-bootstrap/Container"
import Row from "react-bootstrap/Row"
import Col from "react-bootstrap/Col"

function importAll(r) {
    const mapping = {}
    r.keys().map(r).forEach(url=>{
        const {groups: {name}} = url.match(/^.*\/(?<name>.*)\..*\.wav$/)
        mapping[name] = url
    })
    return mapping
}


const soundFileUrls = importAll(require.context('./parawav/', false, /\.wav$/))

class PlayableTD extends React.Component{

    constructor(props) {
        super(props);
        this.player = React.createRef()
    }


    render() {
        return (
            <td className="playable-td" onClick={() => {
                console.log(this.player)
                this.player.play().then()
            }}>
                <Container fluid>
                    <Row>
                        <Col>{this.props.children}</Col>
                        <Col>
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="volume"
                                 className="float-right speaker-icon" role="img" xmlns="http://www.w3.org/2000/svg"
                                 viewBox="0 0 480 512" style={{height: "2em"}}>
                                <path
                                    d="M215.03 71.05L126.06 160H24c-13.26 0-24 10.74-24 24v144c0 13.25 10.74 24 24 24h102.06l88.97 88.95c15.03 15.03 40.97 4.47 40.97-16.97V88.02c0-21.46-25.96-31.98-40.97-16.97zM480 256c0-63.53-32.06-121.94-85.77-156.24-11.19-7.14-26.03-3.82-33.12 7.46s-3.78 26.21 7.41 33.36C408.27 165.97 432 209.11 432 256s-23.73 90.03-63.48 115.42c-11.19 7.14-14.5 22.07-7.41 33.36 6.51 10.36 21.12 15.14 33.12 7.46C447.94 377.94 480 319.53 480 256zm-141.77-76.87c-11.58-6.33-26.19-2.16-32.61 9.45-6.39 11.61-2.16 26.2 9.45 32.61C327.98 228.28 336 241.63 336 256c0 14.38-8.02 27.72-20.92 34.81-11.61 6.41-15.84 21-9.45 32.61 6.43 11.66 21.05 15.8 32.61 9.45 28.23-15.55 45.77-45 45.77-76.88s-17.54-61.32-45.78-76.86z"></path>
                            </svg>
                        </Col>
                        <Col>
                            <audio src={encodeURI(soundFileUrls[this.props.children])} ref={(ref)=>{this.player = ref}}/>
                        </Col>
                    </Row>


                </Container>


            </td>
        )
    }
}



function App() {
    // const rowCount = 4
    // const colCount = 6

    // const screenCenterStyle = {position:'fixed', tops: "50%", left: "50%"}

    return (

        <table className="table table-striped table-dark">
            <thead>
            <tr>
                <th scope="col">Present</th>
                <th scope="col"/>
                <th scope="col"/>
                <th scope="col"/>
                <th scope="col">Future Intentional</th>
            </tr>
            <tr>
                <th scope="col">Person</th>
                <th scope="col">Independent</th>
                <th scope="col">Conjunct</th>
                <th scope="col"/>
                <th scope="col">Person</th>
                <th scope="col">Independent</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>1Sg→3SgO</td>
                <PlayableTD>niwâpamâw</PlayableTD>
                <PlayableTD>ê-wâpamak</PlayableTD>
                <td/>
                <td>1Sg→3SgO</td>
                <PlayableTD>nika-wâpamâw</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>2Sg→3SgO</td>
                <PlayableTD>kiwâpamâw</PlayableTD>
                <PlayableTD>ê-wâpamat</PlayableTD>
                <td/>
                <td>2Sg→3SgO</td>
                <PlayableTD>kika-wâpamâw</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>1Pl→3SgO</td>
                <PlayableTD>niwâpamânân</PlayableTD>
                <PlayableTD>ê-wâpamâyâhk</PlayableTD>
                <td/>
                <td>1Pl→3SgO</td>
                <PlayableTD>nika-wâpamânân</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>12Pl→3SgO</td>
                <PlayableTD>kiwâpamânaw</PlayableTD>
                <PlayableTD>ê-wâpamâyahk</PlayableTD>
                <td/>
                <td>12Pl→3SgO</td>
                <PlayableTD>kika-wâpamânaw</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>2Pl→3SgO</td>
                <PlayableTD>kiwâpamâwâw</PlayableTD>
                <PlayableTD>ê-wâpamâyêk</PlayableTD>
                <td/>
                <td>2Pl→3SgO</td>
                <PlayableTD>kika-wâpamâwâw</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>1Sg→3PlO</td>
                <PlayableTD>niwâpamâwak</PlayableTD>
                <PlayableTD>ê-wâpamakik</PlayableTD>
                <td/>
                <td>1Sg→3PlO</td>
                <PlayableTD>nika-wâpamâwak</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>2Sg→3PlO</td>
                <PlayableTD>kiwâpamâwak</PlayableTD>
                <PlayableTD>ê-wâpamacik</PlayableTD>
                <td/>
                <td>2Sg→3PlO</td>
                <PlayableTD>kika-wâpamâwak</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>1Pl→3PlO</td>
                <PlayableTD>niwâpamânânak</PlayableTD>
                <PlayableTD>ê-wâpamâyâhkik</PlayableTD>
                <td/>
                <td>1Pl→3PlO</td>
                <PlayableTD>nika-wâpamânânak</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>12Pl→3PlO</td>
                <PlayableTD>kiwâpamânawak</PlayableTD>
                <PlayableTD>ê-wâpamâyahkok</PlayableTD>
                <td/>
                <td>12Pl→3PlO</td>
                <PlayableTD>kika-wâpamânawak</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>2Pl→3PlO</td>
                <PlayableTD>kiwâpamâwâwak</PlayableTD>
                <PlayableTD>ê-wâpamâyêkok</PlayableTD>
                <td/>
                <td>2Pl→3PlO</td>
                <PlayableTD>kika-wâpamâwâwak</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>2Sg→1SgO</td>
                <PlayableTD>kiwâpamin</PlayableTD>
                <PlayableTD>ê-wâpamiyan</PlayableTD>
                <td/>
                <td>2Sg→1SgO</td>
                <PlayableTD>kika-wâpamin</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>2Sg→1PlO</td>
                <PlayableTD>kiwâpaminân</PlayableTD>
                <PlayableTD>ê-wâpamiyâhk</PlayableTD>
                <td/>
                <td>2Sg→1PlO</td>
                <PlayableTD>kika-wâpaminân</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>2Pl→1PlO</td>
                <PlayableTD>kiwâpaminân</PlayableTD>
                <PlayableTD>ê-wâpamiyâhk</PlayableTD>
                <td/>
                <td>2Pl→1PlO</td>
                <PlayableTD>kika-wâpaminân</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>2Pl→1SgO</td>
                <PlayableTD>kiwâpaminâwâw</PlayableTD>
                <PlayableTD>ê-wâpamiyêk</PlayableTD>
                <td/>
                <td>2Pl→1SgO</td>
                <PlayableTD>kika-wâpaminâwâw</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Sg→4Sg/PlO</td>
                <PlayableTD>wâpamêw</PlayableTD>
                <PlayableTD>ê-wâpamât</PlayableTD>
                <td/>
                <td>3Sg→4Sg/PlO</td>
                <PlayableTD>ka-wâpamêw</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Pl→4Sg/PlO</td>
                <PlayableTD>wâpamêwak</PlayableTD>
                <PlayableTD>ê-wâpamâcik</PlayableTD>
                <td/>
                <td>3Pl→4Sg/PlO</td>
                <PlayableTD>ka-wâpamêwak</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>4Sg/Pl→5Sg/PlO</td>
                <PlayableTD>wâpamêyiwa</PlayableTD>
                <PlayableTD>ê-wâpamâyit</PlayableTD>
                <td/>
                <td>4Sg/Pl→5Sg/PlO</td>
                <PlayableTD>ka-wâpamêyiwa</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Sg→5Sg/PlO</td>
                <PlayableTD>wâpamimêw</PlayableTD>
                <PlayableTD>ê-wâpamimât</PlayableTD>
                <td/>
                <td>3Sg→5Sg/PlO</td>
                <PlayableTD>ka-wâpamimêw</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Pl→5Sg/PlO</td>
                <PlayableTD>wâpamimêwak</PlayableTD>
                <PlayableTD>ê-wâpamimâcik</PlayableTD>
                <td/>
                <td>3Pl→5Sg/PlO</td>
                <PlayableTD>ka-wâpamimêwak</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>1Sg→4Sg/PlO</td>
                <PlayableTD>niwâpamimâwa</PlayableTD>
                <PlayableTD>ê-wâpamimak</PlayableTD>
                <td/>
                <td>1Sg→4Sg/PlO</td>
                <PlayableTD>nika-wâpamimâwa</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>2Sg→4Sg/PlO</td>
                <PlayableTD>kiwâpamimâwa</PlayableTD>
                <PlayableTD>ê-wâpamimat</PlayableTD>
                <td/>
                <td>2Sg→4Sg/PlO</td>
                <PlayableTD>kika-wâpamimâwa</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>1Pl→4Sg/PlO</td>
                <PlayableTD>niwâpamimânâna</PlayableTD>
                <PlayableTD>ê-wâpamimâyâhk</PlayableTD>
                <td/>
                <td>1Pl→4Sg/PlO</td>
                <PlayableTD>nika-wâpamimânâna</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>12Pl→4Sg/PlO</td>
                <PlayableTD>kiwâpamimânawa</PlayableTD>
                <PlayableTD>ê-wâpamimâyahk</PlayableTD>
                <td/>
                <td>12Pl→4Sg/PlO</td>
                <PlayableTD>kika-wâpamimânawa</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>2Pl→4Sg/PlO</td>
                <PlayableTD>kiwâpamimâwâwa</PlayableTD>
                <PlayableTD>ê-wâpamimâyêk</PlayableTD>
                <td/>
                <td>2Pl→4Sg/PlO</td>
                <PlayableTD>kika-wâpamimâwâwa</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Sg→1SgO</td>
                <PlayableTD>niwâpamik</PlayableTD>
                <PlayableTD>ê-wâpamit</PlayableTD>
                <td/>
                <td>3Sg→1SgO</td>
                <PlayableTD>nika-wâpamik</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Sg→2SgO</td>
                <PlayableTD>kiwâpamik</PlayableTD>
                <PlayableTD>ê-wâpamisk</PlayableTD>
                <td/>
                <td>3Sg→2SgO</td>
                <PlayableTD>kika-wâpamik</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Sg→1PlO</td>
                <PlayableTD>niwâpamikonân</PlayableTD>
                <PlayableTD>ê-wâpamikoyâhk</PlayableTD>
                <td/>
                <td>3Sg→1PlO</td>
                <PlayableTD>nika-wâpamikonân</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Sg→12PlO</td>
                <PlayableTD>kiwâpamikonaw</PlayableTD>
                <PlayableTD>ê-wâpamikoyahk</PlayableTD>
                <td/>
                <td>3Sg→12PlO</td>
                <PlayableTD>kika-wâpamikonaw</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Sg→2PlO</td>
                <PlayableTD>kiwâpamikowâw</PlayableTD>
                <PlayableTD>ê-wâpamikoyêk</PlayableTD>
                <td/>
                <td>3Sg→2PlO</td>
                <PlayableTD>kika-wâpamikowâw</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Pl→1SgO</td>
                <PlayableTD>niwâpamikowak, niwâpamikwak</PlayableTD>
                <PlayableTD>ê-wâpamicik</PlayableTD>
                <td/>
                <td>3Pl→1SgO</td>
                <PlayableTD>nika-wâpamikowak, nika-wâpamikwak</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Pl→2SgO</td>
                <PlayableTD>kiwâpamikowak, kiwâpamikwak</PlayableTD>
                <PlayableTD>ê-wâpamiskik</PlayableTD>
                <td/>
                <td>3Pl→2SgO</td>
                <PlayableTD>kika-wâpamikowak, kika-wâpamikwak</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Pl→1PlO</td>
                <PlayableTD>niwâpamikonânak</PlayableTD>
                <PlayableTD>ê-wâpamikoyâhkik</PlayableTD>
                <td/>
                <td>3Pl→1PlO</td>
                <PlayableTD>nika-wâpamikonânak</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Pl→12PlO</td>
                <PlayableTD>kiwâpamikonawak</PlayableTD>
                <PlayableTD>ê-wâpamikoyahkok</PlayableTD>
                <td/>
                <td>3Pl→12PlO</td>
                <PlayableTD>kika-wâpamikonawak</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>3Pl→2PlO</td>
                <PlayableTD>kiwâpamikowâwak</PlayableTD>
                <PlayableTD>ê-wâpamikoyêkok</PlayableTD>
                <td/>
                <td>3Pl→2PlO</td>
                <PlayableTD>kika-wâpamikowâwak</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>1Sg→2SgO</td>
                <PlayableTD>kiwâpamitin</PlayableTD>
                <PlayableTD>ê-wâpamitân</PlayableTD>
                <td/>
                <td>1Sg→2SgO</td>
                <PlayableTD>kika-wâpamitin</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>1Pl→2SgO</td>
                <PlayableTD>kiwâpamitinân</PlayableTD>
                <PlayableTD>ê-wâpamitâhk</PlayableTD>
                <td/>
                <td>1Pl→2SgO</td>
                <PlayableTD>kika-wâpamitinân</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>1Pl→2PlO</td>
                <PlayableTD>kiwâpamitinân</PlayableTD>
                <PlayableTD>ê-wâpamitâhk</PlayableTD>
                <td/>
                <td>1Pl→2PlO</td>
                <PlayableTD>kika-wâpamitinân</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>1Sg→2PlO</td>
                <PlayableTD>kiwâpamitinâwâw</PlayableTD>
                <PlayableTD>ê-wâpamitakok</PlayableTD>
                <td/>
                <td>1Sg→2PlO</td>
                <PlayableTD>kika-wâpamitinâwâw</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>4Sg/Pl→3SgO</td>
                <PlayableTD>wâpamik, wâpamikow</PlayableTD>
                <PlayableTD>ê-wâpamikot</PlayableTD>
                <td/>
                <td>4Sg/Pl→3SgO</td>
                <PlayableTD>ka-wâpamik, ka-wâpamikow</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>4Sg/Pl→3PlO</td>
                <PlayableTD>wâpamikowak, wâpamikwak</PlayableTD>
                <PlayableTD>ê-wâpamikocik</PlayableTD>
                <td/>
                <td>4Sg/Pl→3PlO</td>
                <PlayableTD>ka-wâpamikowak, ka-wâpamikwak</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>5Sg/Pl→4Sg/PlO</td>
                <PlayableTD>wâpamikoyiwa</PlayableTD>
                <PlayableTD>ê-wâpamikoyit</PlayableTD>
                <td/>
                <td>5Sg/Pl→4Sg/PlO</td>
                <PlayableTD>ka-wâpamikoyiwa</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>4Sg/Pl→1SgO</td>
                <PlayableTD>niwâpamikoyiwa</PlayableTD>
                <PlayableTD>ê-wâpamimit</PlayableTD>
                <td/>
                <td>4Sg/Pl→1SgO</td>
                <PlayableTD>nika-wâpamikoyiwa</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>4Sg/Pl→2SgO</td>
                <PlayableTD>kiwâpamikoyiwa</PlayableTD>
                <PlayableTD>ê-wâpamimisk</PlayableTD>
                <td/>
                <td>4Sg/Pl→2SgO</td>
                <PlayableTD>kika-wâpamikoyiwa</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>4Sg/Pl→1PlO</td>
                <PlayableTD>niwâpamikonâna</PlayableTD>
                <PlayableTD>ê-wâpamikoyâhk</PlayableTD>
                <td/>
                <td>4Sg/Pl→1PlO</td>
                <PlayableTD>nika-wâpamikonâna</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>4Sg/Pl→2PlO</td>
                <PlayableTD>kiwâpamikowâwa</PlayableTD>
                <PlayableTD>ê-wâpamikoyêk</PlayableTD>
                <td/>
                <td>4Sg/Pl→2PlO</td>
                <PlayableTD>kika-wâpamikowâwa</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td>4Sg/Pl→12PlO</td>
                <PlayableTD>kiwâpamikonawa</PlayableTD>
                <PlayableTD>ê-wâpamikoyahk</PlayableTD>
                <td/>
                <td>4Sg/Pl→12PlO</td>
                <PlayableTD>kika-wâpamikonawa</PlayableTD>
                <td/>
            </tr>
            <tr>
                <td/>
                <td/>
                <td/>
                <td/>
                <td/>
                <td/>
                <td/>
            </tr>
            <tr>
                <th scope="col">Past</th>
                <th scope="col"/>
                <th scope="col"/>
                <th scope="col"/>
                <th scope="col">Future Definite</th>
            </tr>
            <tr>
                <th scope="col">Person</th>
                <th scope="col">Independent</th>
                <th scope="col">Conjunct</th>
                <th scope="col"/>
                <th scope="col">Person</th>
                <th scope="col">Independent</th>
                <th scope="col">Conjunct</th>
            </tr>
            <tr>
                <td>1Sg→3SgO</td>
                <PlayableTD>nikî-wâpamâw</PlayableTD>
                <PlayableTD>ê-kî-wâpamak</PlayableTD>
                <td/>
                <td>1Sg→3SgO</td>
                <PlayableTD>niwî-wâpamâw</PlayableTD>
                <PlayableTD>ê-wî-wâpamak</PlayableTD>
            </tr>
            <tr>
                <td>2Sg→3SgO</td>
                <PlayableTD>kikî-wâpamâw</PlayableTD>
                <PlayableTD>ê-kî-wâpamat</PlayableTD>
                <td/>
                <td>2Sg→3SgO</td>
                <PlayableTD>kiwî-wâpamâw</PlayableTD>
                <PlayableTD>ê-wî-wâpamat</PlayableTD>
            </tr>
            <tr>
                <td>1Pl→3SgO</td>
                <PlayableTD>nikî-wâpamânân</PlayableTD>
                <PlayableTD>ê-kî-wâpamâyâhk</PlayableTD>
                <td/>
                <td>1Pl→3SgO</td>
                <PlayableTD>niwî-wâpamânân</PlayableTD>
                <PlayableTD>ê-wî-wâpamâyâhk</PlayableTD>
            </tr>
            <tr>
                <td>12Pl→3SgO</td>
                <PlayableTD>kikî-wâpamânaw</PlayableTD>
                <PlayableTD>ê-kî-wâpamâyahk</PlayableTD>
                <td/>
                <td>12Pl→3SgO</td>
                <PlayableTD>kiwî-wâpamânaw</PlayableTD>
                <PlayableTD>ê-wî-wâpamâyahk</PlayableTD>
            </tr>
            <tr>
                <td>2Pl→3SgO</td>
                <PlayableTD>kikî-wâpamâwâw</PlayableTD>
                <PlayableTD>ê-kî-wâpamâyêk</PlayableTD>
                <td/>
                <td>2Pl→3SgO</td>
                <PlayableTD>kiwî-wâpamâwâw</PlayableTD>
                <PlayableTD>ê-wî-wâpamâyêk</PlayableTD>
            </tr>
            <tr>
                <td>1Sg→3PlO</td>
                <PlayableTD>nikî-wâpamâwak</PlayableTD>
                <PlayableTD>ê-kî-wâpamakik</PlayableTD>
                <td/>
                <td>1Sg→3PlO</td>
                <PlayableTD>niwî-wâpamâwak</PlayableTD>
                <PlayableTD>ê-wî-wâpamakik</PlayableTD>
            </tr>
            <tr>
                <td>2Sg→3PlO</td>
                <PlayableTD>kikî-wâpamâwak</PlayableTD>
                <PlayableTD>ê-kî-wâpamacik</PlayableTD>
                <td/>
                <td>2Sg→3PlO</td>
                <PlayableTD>kiwî-wâpamâwak</PlayableTD>
                <PlayableTD>ê-wî-wâpamacik</PlayableTD>
            </tr>
            <tr>
                <td>1Pl→3PlO</td>
                <PlayableTD>nikî-wâpamânânak</PlayableTD>
                <PlayableTD>ê-kî-wâpamâyâhkik</PlayableTD>
                <td/>
                <td>1Pl→3PlO</td>
                <PlayableTD>niwî-wâpamânânak</PlayableTD>
                <PlayableTD>ê-wî-wâpamâyâhkik</PlayableTD>
            </tr>
            <tr>
                <td>12Pl→3PlO</td>
                <PlayableTD>kikî-wâpamânawak</PlayableTD>
                <PlayableTD>ê-kî-wâpamâyahkok</PlayableTD>
                <td/>
                <td>12Pl→3PlO</td>
                <PlayableTD>kiwî-wâpamânawak</PlayableTD>
                <PlayableTD>ê-wî-wâpamâyahkok</PlayableTD>
            </tr>
            <tr>
                <td>2Pl→3PlO</td>
                <PlayableTD>kikî-wâpamâwâwak</PlayableTD>
                <PlayableTD>ê-kî-wâpamâyêkok</PlayableTD>
                <td/>
                <td>2Pl→3PlO</td>
                <PlayableTD>kiwî-wâpamâwâwak</PlayableTD>
                <PlayableTD>ê-wî-wâpamâyêkok</PlayableTD>
            </tr>
            <tr>
                <td>2Sg→1SgO</td>
                <PlayableTD>kikî-wâpamin</PlayableTD>
                <PlayableTD>ê-kî-wâpamiyan</PlayableTD>
                <td/>
                <td>2Sg→1SgO</td>
                <PlayableTD>kiwî-wâpamin</PlayableTD>
                <PlayableTD>ê-wî-wâpamiyan</PlayableTD>
            </tr>
            <tr>
                <td>2Sg→1PlO</td>
                <PlayableTD>kikî-wâpaminân</PlayableTD>
                <PlayableTD>ê-kî-wâpamiyâhk</PlayableTD>
                <td/>
                <td>2Sg→1PlO</td>
                <PlayableTD>kiwî-wâpaminân</PlayableTD>
                <PlayableTD>ê-wî-wâpamiyâhk</PlayableTD>
            </tr>
            <tr>
                <td>2Pl→1PlO</td>
                <PlayableTD>kikî-wâpaminân</PlayableTD>
                <PlayableTD>ê-kî-wâpamiyâhk</PlayableTD>
                <td/>
                <td>2Pl→1PlO</td>
                <PlayableTD>kiwî-wâpaminân</PlayableTD>
                <PlayableTD>ê-wî-wâpamiyâhk</PlayableTD>
            </tr>
            <tr>
                <td>2Pl→1SgO</td>
                <PlayableTD>kikî-wâpaminâwâw</PlayableTD>
                <PlayableTD>ê-kî-wâpamiyêk</PlayableTD>
                <td/>
                <td>2Pl→1SgO</td>
                <PlayableTD>kiwî-wâpaminâwâw</PlayableTD>
                <PlayableTD>ê-wî-wâpamiyêk</PlayableTD>
            </tr>
            <tr>
                <td>3Sg→4Sg/PlO</td>
                <PlayableTD>kî-wâpamêw</PlayableTD>
                <PlayableTD>ê-kî-wâpamât</PlayableTD>
                <td/>
                <td>3Sg→4Sg/PlO</td>
                <PlayableTD>wî-wâpamêw</PlayableTD>
                <PlayableTD>ê-wî-wâpamât</PlayableTD>
            </tr>
            <tr>
                <td>3Pl→4Sg/PlO</td>
                <PlayableTD>kî-wâpamêwak</PlayableTD>
                <PlayableTD>ê-kî-wâpamâcik</PlayableTD>
                <td/>
                <td>3Pl→4Sg/PlO</td>
                <PlayableTD>wî-wâpamêwak</PlayableTD>
                <PlayableTD>ê-wî-wâpamâcik</PlayableTD>
            </tr>
            <tr>
                <td>4Sg/Pl→5Sg/PlO</td>
                <PlayableTD>kî-wâpamêyiwa</PlayableTD>
                <PlayableTD>ê-kî-wâpamâyit</PlayableTD>
                <td/>
                <td>4Sg/Pl→5Sg/PlO</td>
                <PlayableTD>wî-wâpamêyiwa</PlayableTD>
                <PlayableTD>ê-wî-wâpamâyit</PlayableTD>
            </tr>
            <tr>
                <td>3Sg→5Sg/PlO</td>
                <PlayableTD>kî-wâpamimêw</PlayableTD>
                <PlayableTD>ê-kî-wâpamimât</PlayableTD>
                <td/>
                <td>3Sg→5Sg/PlO</td>
                <PlayableTD>wî-wâpamimêw</PlayableTD>
                <PlayableTD>ê-wî-wâpamimât</PlayableTD>
            </tr>
            <tr>
                <td>3Pl→5Sg/PlO</td>
                <PlayableTD>kî-wâpamimêwak</PlayableTD>
                <PlayableTD>ê-kî-wâpamimâcik</PlayableTD>
                <td/>
                <td>3Pl→5Sg/PlO</td>
                <PlayableTD>wî-wâpamimêwak</PlayableTD>
                <PlayableTD>ê-wî-wâpamimâcik</PlayableTD>
            </tr>
            <tr>
                <td>1Sg→4Sg/PlO</td>
                <PlayableTD>nikî-wâpamimâwa</PlayableTD>
                <PlayableTD>ê-kî-wâpamimak</PlayableTD>
                <td/>
                <td>1Sg→4Sg/PlO</td>
                <PlayableTD>niwî-wâpamimâwa</PlayableTD>
                <PlayableTD>ê-wî-wâpamimak</PlayableTD>
            </tr>
            <tr>
                <td>2Sg→4Sg/PlO</td>
                <PlayableTD>kikî-wâpamimâwa</PlayableTD>
                <PlayableTD>ê-kî-wâpamimat</PlayableTD>
                <td/>
                <td>2Sg→4Sg/PlO</td>
                <PlayableTD>kiwî-wâpamimâwa</PlayableTD>
                <PlayableTD>ê-wî-wâpamimat</PlayableTD>
            </tr>
            <tr>
                <td>1Pl→4Sg/PlO</td>
                <PlayableTD>nikî-wâpamimânâna</PlayableTD>
                <PlayableTD>ê-kî-wâpamimâyâhk</PlayableTD>
                <td/>
                <td>1Pl→4Sg/PlO</td>
                <PlayableTD>niwî-wâpamimânâna</PlayableTD>
                <PlayableTD>ê-wî-wâpamimâyâhk</PlayableTD>
            </tr>
            <tr>
                <td>12Pl→4Sg/PlO</td>
                <PlayableTD>kikî-wâpamimânawa</PlayableTD>
                <PlayableTD>ê-kî-wâpamimâyahk</PlayableTD>
                <td/>
                <td>12Pl→4Sg/PlO</td>
                <PlayableTD>kiwî-wâpamimânawa</PlayableTD>
                <PlayableTD>ê-wî-wâpamimâyahk</PlayableTD>
            </tr>
            <tr>
                <td>2Pl→4Sg/PlO</td>
                <PlayableTD>kikî-wâpamimâwâwa</PlayableTD>
                <PlayableTD>ê-kî-wâpamimâyêk</PlayableTD>
                <td/>
                <td>2Pl→4Sg/PlO</td>
                <PlayableTD>kiwî-wâpamimâwâwa</PlayableTD>
                <PlayableTD>ê-wî-wâpamimâyêk</PlayableTD>
            </tr>
            <tr>
                <td>3Sg→1SgO</td>
                <PlayableTD>nikî-wâpamik</PlayableTD>
                <PlayableTD>ê-kî-wâpamit</PlayableTD>
                <td/>
                <td>3Sg→1SgO</td>
                <PlayableTD>niwî-wâpamik</PlayableTD>
                <PlayableTD>ê-wî-wâpamit</PlayableTD>
            </tr>
            <tr>
                <td>3Sg→2SgO</td>
                <PlayableTD>kikî-wâpamik</PlayableTD>
                <PlayableTD>ê-kî-wâpamisk</PlayableTD>
                <td/>
                <td>3Sg→2SgO</td>
                <PlayableTD>kiwî-wâpamik</PlayableTD>
                <PlayableTD>ê-wî-wâpamisk</PlayableTD>
            </tr>
            <tr>
                <td>3Sg→1PlO</td>
                <PlayableTD>nikî-wâpamikonân</PlayableTD>
                <PlayableTD>ê-kî-wâpamikoyâhk</PlayableTD>
                <td/>
                <td>3Sg→1PlO</td>
                <PlayableTD>niwî-wâpamikonân</PlayableTD>
                <PlayableTD>ê-wî-wâpamikoyâhk</PlayableTD>
            </tr>
            <tr>
                <td>3Sg→12PlO</td>
                <PlayableTD>kikî-wâpamikonaw</PlayableTD>
                <PlayableTD>ê-kî-wâpamikoyahk</PlayableTD>
                <td/>
                <td>3Sg→12PlO</td>
                <PlayableTD>kiwî-wâpamikonaw</PlayableTD>
                <PlayableTD>ê-wî-wâpamikoyahk</PlayableTD>
            </tr>
            <tr>
                <td>3Sg→2PlO</td>
                <PlayableTD>kikî-wâpamikowâw</PlayableTD>
                <PlayableTD>ê-kî-wâpamikoyêk</PlayableTD>
                <td/>
                <td>3Sg→2PlO</td>
                <PlayableTD>kiwî-wâpamikowâw</PlayableTD>
                <PlayableTD>ê-wî-wâpamikoyêk</PlayableTD>
            </tr>
            <tr>
                <td>3Pl→1SgO</td>
                <PlayableTD>nikî-wâpamikowak, nikî-wâpamikwak</PlayableTD>
                <PlayableTD>ê-kî-wâpamicik</PlayableTD>
                <td/>
                <td>3Pl→1SgO</td>
                <PlayableTD>niwî-wâpamikowak, niwî-wâpamikwak</PlayableTD>
                <PlayableTD>ê-wî-wâpamicik</PlayableTD>
            </tr>
            <tr>
                <td>3Pl→2SgO</td>
                <PlayableTD>kikî-wâpamikowak, kikî-wâpamikwak</PlayableTD>
                <PlayableTD>ê-kî-wâpamiskik</PlayableTD>
                <td/>
                <td>3Pl→2SgO</td>
                <PlayableTD>kiwî-wâpamikowak, kiwî-wâpamikwak</PlayableTD>
                <PlayableTD>ê-wî-wâpamiskik</PlayableTD>
            </tr>
            <tr>
                <td>3Pl→1PlO</td>
                <PlayableTD>nikî-wâpamikonânak</PlayableTD>
                <PlayableTD>ê-kî-wâpamikoyâhkik</PlayableTD>
                <td/>
                <td>3Pl→1PlO</td>
                <PlayableTD>niw��-wâpamikonânak</PlayableTD>
                <PlayableTD>ê-wî-wâpamikoyâhkik</PlayableTD>
            </tr>
            <tr>
                <td>3Pl→12PlO</td>
                <PlayableTD>kikî-wâpamikonawak</PlayableTD>
                <PlayableTD>ê-kî-wâpamikoyahkok</PlayableTD>
                <td/>
                <td>3Pl→12PlO</td>
                <PlayableTD>kiwî-wâpamikonawak</PlayableTD>
                <PlayableTD>ê-wî-wâpamikoyahkok</PlayableTD>
            </tr>
            <tr>
                <td>3Pl→2PlO</td>
                <PlayableTD>kikî-wâpamikowâwak</PlayableTD>
                <PlayableTD>ê-kî-wâpamikoyêkok</PlayableTD>
                <td/>
                <td>3Pl→2PlO</td>
                <PlayableTD>kiwî-wâpamikowâwak</PlayableTD>
                <PlayableTD>ê-wî-wâpamikoyêkok</PlayableTD>
            </tr>
            <tr>
                <td>1Sg→2SgO</td>
                <PlayableTD>kikî-wâpamitin</PlayableTD>
                <PlayableTD>ê-kî-wâpamitân</PlayableTD>
                <td/>
                <td>1Sg→2SgO</td>
                <PlayableTD>kiwî-wâpamitin</PlayableTD>
                <PlayableTD>ê-wî-wâpamitân</PlayableTD>
            </tr>
            <tr>
                <td>1Pl→2SgO</td>
                <PlayableTD>kikî-wâpamitinân</PlayableTD>
                <PlayableTD>ê-kî-wâpamitâhk</PlayableTD>
                <td/>
                <td>1Pl→2SgO</td>
                <PlayableTD>kiwî-wâpamitinân</PlayableTD>
                <PlayableTD>ê-wî-wâpamitâhk</PlayableTD>
            </tr>
            <tr>
                <td>1Pl→2PlO</td>
                <PlayableTD>kikî-wâpamitinân</PlayableTD>
                <PlayableTD>ê-kî-wâpamitâhk</PlayableTD>
                <td/>
                <td>1Pl→2PlO</td>
                <PlayableTD>kiwî-wâpamitinân</PlayableTD>
                <PlayableTD>ê-wî-wâpamitâhk</PlayableTD>
            </tr>
            <tr>
                <td>1Sg→2PlO</td>
                <PlayableTD>kikî-wâpamitinâwâw</PlayableTD>
                <PlayableTD>ê-kî-wâpamitakok</PlayableTD>
                <td/>
                <td>1Sg→2PlO</td>
                <PlayableTD>kiwî-wâpamitinâwâw</PlayableTD>
                <PlayableTD>ê-wî-wâpamitakok</PlayableTD>
            </tr>
            <tr>
                <td>4Sg/Pl→3SgO</td>
                <PlayableTD>kî-wâpamik, kî-wâpamikow</PlayableTD>
                <PlayableTD>ê-kî-wâpamikot</PlayableTD>
                <td/>
                <td>4Sg/Pl→3SgO</td>
                <PlayableTD>wî-wâpamik, wî-wâpamikow</PlayableTD>
                <PlayableTD>ê-wî-wâpamikot</PlayableTD>
            </tr>
            <tr>
                <td>4Sg/Pl→3PlO</td>
                <PlayableTD>kî-wâpamikowak, kî-wâpamikwak</PlayableTD>
                <PlayableTD>ê-kî-wâpamikocik</PlayableTD>
                <td/>
                <td>4Sg/Pl→3PlO</td>
                <PlayableTD>wî-wâpamikowak, wî-wâpamikwak</PlayableTD>
                <PlayableTD>ê-wî-wâpamikocik</PlayableTD>
            </tr>
            <tr>
                <td>5Sg/Pl→4Sg/PlO</td>
                <PlayableTD>kî-wâpamikoyiwa</PlayableTD>
                <PlayableTD>ê-kî-wâpamikoyit</PlayableTD>
                <td/>
                <td>5Sg/Pl→4Sg/PlO</td>
                <PlayableTD>wî-wâpamikoyiwa</PlayableTD>
                <PlayableTD>ê-wî-wâpamikoyit</PlayableTD>
            </tr>
            <tr>
                <td>4Sg/Pl→1SgO</td>
                <PlayableTD>nikî-wâpamikoyiwa</PlayableTD>
                <PlayableTD>ê-kî-wâpamimit</PlayableTD>
                <td/>
                <td>4Sg/Pl→1SgO</td>
                <PlayableTD>niwî-wâpamikoyiwa</PlayableTD>
                <PlayableTD>ê-wî-wâpamimit</PlayableTD>
            </tr>
            <tr>
                <td>4Sg/Pl→2SgO</td>
                <PlayableTD>kikî-wâpamikoyiwa</PlayableTD>
                <PlayableTD>ê-kî-wâpamimisk</PlayableTD>
                <td/>
                <td>4Sg/Pl→2SgO</td>
                <PlayableTD>kiwî-wâpamikoyiwa</PlayableTD>
                <PlayableTD>ê-wî-wâpamimisk</PlayableTD>
            </tr>
            <tr>
                <td>4Sg/Pl→1PlO</td>
                <PlayableTD>nikî-wâpamikonâna</PlayableTD>
                <PlayableTD>ê-kî-wâpamikoyâhk</PlayableTD>
                <td/>
                <td>4Sg/Pl→1PlO</td>
                <PlayableTD>niwî-wâpamikonâna</PlayableTD>
                <PlayableTD>ê-wî-wâpamikoyâhk</PlayableTD>
            </tr>
            <tr>
                <td>4Sg/Pl→2PlO</td>
                <PlayableTD>kikî-wâpamikowâwa</PlayableTD>
                <PlayableTD>ê-kî-wâpamikoyêk</PlayableTD>
                <td/>
                <td>4Sg/Pl→2PlO</td>
                <PlayableTD>kiwî-wâpamikowâwa</PlayableTD>
                <PlayableTD>ê-wî-wâpamikoyêk</PlayableTD>
            </tr>
            <tr>
                <td>4Sg/Pl→12PlO</td>
                <PlayableTD>kikî-wâpamikonawa</PlayableTD>
                <PlayableTD>ê-kî-wâpamikoyahk</PlayableTD>
                <td/>
                <td>4Sg/Pl→12PlO</td>
                <PlayableTD>kiwî-wâpamikonawa</PlayableTD>
                <PlayableTD>ê-wî-wâpamikoyahk</PlayableTD>
            </tr>


            </tbody>
        </table>


    )
}

export default App
